### PR TITLE
Adding improved support and documentation for PasteDeploy pipeline

### PR DESCRIPTION
**Pull request by davidjb**
1. Coerce string-based boolean values from configuration (eg Paste ini files)
2. Add documentation to readme
3. Smile because raptorization never gets old.

### CODE REVIEW

**Comment by ralphbean** [comment]
Thanks @davidjb!

**Comment by davidjb** [comment]
Was there a change log present or something similar - suspect I might have
a few more things to contribute.

Thanks.

On Thursday, September 6, 2012, Ralph Bean wrote:

> Thanks @davidjb https://github.com/davidjb!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ralphbean/raptorizemw/pull/3#issuecomment-8331590.

## 

Sent from mobile device - please excuse typos.

**Comment by ralphbean** [comment]
Oh, I haven't bothered keeping a changelog.

Although, I suppose it is best practice.  If you'd like to start one I'd be glad to include it.

**Comment by ralphbean** [comment]
And/or an AUTHORS file.  :)

**Comment by davidjb** [comment]
I'll see what I can come up with.  Cheers!

**Pull request merged**
